# Generated by Django 5.1.6 on 2025-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0014_news_short_description_en_news_short_description_uk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='givenFrom',
            new_name='infoFrom',
        ),
        migrations.RemoveField(
            model_name='news',
            name='givenFromUrl',
        ),
        migrations.AddField(
            model_name='news',
            name='isGiven',
            field=models.BooleanField(default=False, verbose_name='Чи взята де інде стаття'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наза статті'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наза статті'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Наза статті'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва товару'),
        ),
    ]
